# Main config file for icon theme.
theme = "hugo-icon"
baseURL = "http://www.oviyum.com/"
languageCode = "en-AU"
title = "OVIYUM Technologies"
publishDir = "/var/www"

# Metadata
[params]
  author = "Oviyum"
  description = "Cloud, Mobile, Ai"

# Hero section (from here on is for icon theme)
[params.hero]
  img = "images/home.jpg"
  title = "We <b>Engineer</b> ideas."
  description = "An outsourced product development company"

# Navigation section
[params.nav]
  mission = "Technology"
  services = "Our work"
  team = "People"
  partners = "Partners"  
  contact = "Get In Touch"
  hiring = "We are hiring!"  
  # Include logo instead if HOME:
  logo = "images/logo.png"

# Mission section
[params.mission]
  enable = true

  [params.mission.images]
    enable = true

    [[params.mission.images.list]]
      img = "images/t1.jpg"
    [[params.mission.images.list]]
      img = "images/t2.jpg"
    [[params.mission.images.list]]
      img = "images/t3.jpg"
    [[params.mission.images.list]]
      img = "images/t4.jpg"

  [[params.mission.item]]
    weight = 1
    name = "marketing"
    title = "Cloud & Mobile"
    subtitle = "Gain business agility, embrace the mobile & cloud computing revolution"
    description = "<p>We use best in class cloud technologies and native application development strategies.Our emphasis on right software engineering principles and culture delivers a high quality product for you.</p><ul class='checked'><li>Cloud-enabled application development</li><li>Cloud integration</li><li>iOs</li><li>Android</li></ul><p><a href='#' class='btn btn-primary btn-outline fh5co-content-nav' data-nav-section='contact'>Get In Touch</a></p>"

  [[params.mission.item]]
    weight = 2
    name = "analysis"
    title = "AI & Vision"
    subtitle = "Building smart and visually intelligent systems"
    description = "<p>Your apps and workflows can be significantly more intuitive and efficient using AI & Computer Vision. Oviyum can boost your business and simplify customer experiences leveraging the best of algorithms - cloud or on premise. </p><ul class='checked'><li>Deep Learning</li><li>Visual Processing</li><li>Neural Computing</li></ul><p><a href='#' class='btn btn-primary btn-outline fh5co-content-nav' data-nav-section='contact'>Get In Touch</a></p>"

  [[params.mission.item]]
    weight = 3
    name = "strategy"
    title = "Hardware"
    subtitle = "Looking to build a solution that requires hardware?"
    description = "<p>Consumer experiences can become significantly more intuitive with tangible extensions. They can be redefined with hardware at the core of your strategy. At the same time building hardware is multi-disciplinary exercise. Our expertise in design thinking & prototyping can help bring your idea to life.</p><ul class='checked'><li>Consulting</li><li>Prototyping</li><li>Support for manufacturing</li></ul><p><a href='#' class='btn btn-primary btn-outline fh5co-content-nav' data-nav-section='contact'>Get In Touch</a></p>"


# Services section
[params.services]
  enable = true
  # video = true
  # vidlink = "https://vimeo.com/channels/staffpicks/93951774"
  title = "Our Work"
  description = "Products that we have helped build"


  [[params.services.item]]
    icon = "icon-rocket"
    title = "Fleetfoot"
    description = "FleetFoot is a fully integrated fleet management platform on the cloud, that provides a scalable, end-to end solution to the Fleet Rental Service Industry."

  [[params.services.item]]
    icon = "icon-support"
    title = "NetLite"
    description = "Netlite is a Volktek's embedded Element Management System that allows users to view the topology map of connected devices and neighboring switches along with the link status."

# Work section
[params.work]
  enable = false

  [[params.work.item]]
    title = "Consectetur adipisicing"
    subtitle = "Web Design"
    img = "images/img_1.jpg"

  [[params.work.item]]
    title = "Consectetur adipisicing"
    subtitle = "Web Design"
    img = "images/img_2.jpg"

  [[params.work.item]]
    title = "Consectetur adipisicing"
    subtitle = "Web Design"
    img = "images/img_3.jpg"

  [[params.work.item]]
    title = "Consectetur adipisicing"
    subtitle = "Web Design"
    img = "images/img_2.jpg"

  [[params.work.item]]
    title = "Consectetur adipisicing"
    subtitle = "Web Design"
    img = "images/img_3.jpg"

  [[params.work.item]]
    title = "Consectetur adipisicing"
    subtitle = "Web Design"
    img = "images/img_2.jpg"

  [[params.work.item]]
    title = "Consectetur adipisicing"
    subtitle = "Web Design"
    img = "images/img_3.jpg"

  [[params.work.item]]
    title = "Consectetur adipisicing"
    subtitle = "Web Design"
    img = "images/img_4.jpg"

# Team section
[params.team]
   enable = true
  title = "Meet The Team"
  description = "Lorem ipsum dolor sit amet consectetur adipisicing elit. Eveniet nam itaque ipsam iste provident quo ipsam iste provident."

  [[params.team.item]]
    name = "Jean Doe"
    position = "Chief legend"
    description = "Lorem ipsum dolor sit amet consectetur adipisicing elit. Eveniet nam itaque ipsam iste provident quo ipsam iste provident."
    img = "images/person1.jpg"
    facebook = "#"
    twitter = "#"
    dribbble = "#"
    instagram = "#"
    github = "#"
    linkedin = "#"

  [[params.team.item]]
    name = "Alice Doe"
    position = "Chief overlord"
    description = "Lorem ipsum dolor sit amet consectetur adipisicing elit. Eveniet nam itaque ipsam iste provident quo ipsam iste provident."
    img = "images/person2.jpg"
    facebook = "#"
    twitter = "#"
    dribbble = "#"
    instagram = "#"
    github = "#"

  [[params.team.item]]
    name = "John Doe"
    position = "Chief haranguer"
    description = "Lorem ipsum dolor sit amet consectetur adipisicing elit. Eveniet nam itaque ipsam iste provident quo ipsam iste provident."
    img = "images/person3.jpg"
    facebook = "#"
    twitter = "#"
    dribbble = "#"
    instagram = "#"
    github = "#"

  # [[params.team.item]]
  #   name = "Jason Doe"
  #   position = "Chief haranguer"
  #   description = "Lorem ipsum dolor sit amet consectetur adipisicing elit. Eveniet nam itaque ipsam iste provident quo ipsam iste provident."
  #   img = "images/person3.jpg"
  #   facebook = "#"
  #   twitter = "#"
  #   dribbble = "#"
  #   instagram = "#"
  #   github = "#"

# Contact section
[params.contact]
  enable = true
  title = "Get In Touch"
  message = "For any clarification or inquiry on how Oviyum can assist you, please contact us."

# Hiring section
[params.hiring]
  enable = true
  title = "Hiring"
  message = "For any clarification or inquiry on how Oviyum can assist you, please contact us."

# Partners section
[params.partners]
  enable = false
  title = "Partners"
  message = "For any clarification or inquiry on how Oviyum can assist you, please contact us."



# Footer section
# Note here that the copyright and attribution statement must remain as part of the license agreement. If you wish to remove this, please contact freehtml5 and pay for a professional license.
[params.footer]
  enable = true
  note = "<p><small>&copy; 2016 Oviyum Technologies. All Rights Reserved. </small></p>"
  github = "https://github.com/Oviyum"
  # twitter = "#"
  # facebook = "#"
  # vine = "#"
  linkedin = "#"
  # instagram = "#"
